- name: create ec2 instances and route 53 records
  hosts: local
  connection: local
  vars: 
      subnet_id: "subnet-038f7624321ae7a46"
      ami_id: "ami-09c813fb71547fc4f"
      sg_group: "sg-0f2ec98b878c6d63f"
      instances:
      - mysql
      - backend
      - frontend
      zone: "gopi-81s.online"
  tasks: 
  - name: installing boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9

  - name: creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_group }}"
      image_id: "{{ ami_id }}"
    loop: "{{instances}}"
    register: ec2_instances

  - name: checking the output of instances
    ansible.builtin.debug:
     msg: " {{ec2_instances}}"


  - name: creating route 53 A records for private ip
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}"

  - name: creating route 53 A records for public ip
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address}}"
      wait: true
      overwrite: true
    loop: "{{ec2_instances.results}}"
    when: item.item== "frontend"

