- name: frontend config using ansible
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  
  