- name: set up configuration for database
  hosts: mysql
  become: yes
  vars:
      login_user: root
      mysql_root_password: ExpenseApp@1
      login_host: "mysql.gopi-81s.online"
  tasks:
  - name: installing mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: starting mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: installing PyMySQL using pip
    ansible.builtin.pip:
      name: PyMySQL
      state: present
      executable: pip3.9

  -  name: connect mysql-server
     community.mysql.mysql_info:
       login_user: "{{ login_user }}"
       login_password: "{{ mysql_root_password }}"
       login_host: "{{ login_host }}"
     ignore_errors: true
     register: mysql_info

  - name: mysql info
    ansible.builtin.debug:
       msg: "{{ mysql_info }}" 

  - name: setup mysql root password
    ansible.builtin.command: mysql_secure_installation --set--root-pass {{ mysql_root_password }}
    when: mysql_info.failed is true
